# ============================================================
# COMPANIES.PY — All 25 Company Career Page Configurations
# Each company has:
#   - name        : Company name
#   - search_url  : Direct URL to their job search page
#   - search_type : How to search (url_param / google_fallback)
#   - domain      : Industry domain
#   - color       : For email formatting
# ============================================================

COMPANIES = [

    # ── TIER 1 MNCs ──
    {
        "id": "siemens",
        "name": "Siemens India",
        "emoji": "⚙️",
        "domain": "Tech / Automation",
        "color": "#00d4aa",
        "search_url": "https://jobs.siemens.com/careers?query=project+manager&location=India",
        "job_card_selector": "[data-ph-at-id='job-item']",
        "title_selector": "[data-ph-at-id='job-title']",
        "fallback_url": "https://www.google.com/search?q=site:jobs.siemens.com+project+manager+India",
    },
    {
        "id": "honeywell",
        "name": "Honeywell India",
        "emoji": "🏗️",
        "domain": "Building Tech",
        "color": "#f0a30a",
        "search_url": "https://careers.honeywell.com/us/en/search-results?keywords=project+manager&location=India",
        "job_card_selector": ".jobs-list-item",
        "title_selector": ".job-title",
        "fallback_url": "https://www.google.com/search?q=site:careers.honeywell.com+project+manager+India",
    },
    {
        "id": "abb",
        "name": "ABB India",
        "emoji": "🤖",
        "domain": "Robotics & Automation",
        "color": "#ef4444",
        "search_url": "https://careers.abb.com/global/en/search-results?keywords=project+manager&location=India",
        "job_card_selector": ".job-item",
        "title_selector": ".job-name",
        "fallback_url": "https://www.google.com/search?q=site:careers.abb.com+project+manager+India",
    },
    {
        "id": "ge",
        "name": "GE Aerospace / GE Vernova",
        "emoji": "✈️",
        "domain": "Aerospace & Energy",
        "color": "#3d7fff",
        "search_url": "https://jobs.gecareers.com/global/en/search-results?keywords=project+manager&location=India",
        "job_card_selector": ".job-tile",
        "title_selector": ".job-title",
        "fallback_url": "https://www.google.com/search?q=site:jobs.gecareers.com+project+manager+India",
    },
    {
        "id": "boeing",
        "name": "Boeing India",
        "emoji": "🛩️",
        "domain": "Aerospace",
        "color": "#1d4ed8",
        "search_url": "https://jobs.boeing.com/search-jobs/project%20manager/185/1",
        "job_card_selector": ".job-list-item",
        "title_selector": ".job-title",
        "fallback_url": "https://www.google.com/search?q=site:jobs.boeing.com+project+manager+India",
    },
    {
        "id": "rtx",
        "name": "RTX / Raytheon India",
        "emoji": "🚀",
        "domain": "Aerospace & Defence",
        "color": "#6366f1",
        "search_url": "https://careers.rtx.com/global/en/search-results?keywords=project+manager&location=India",
        "job_card_selector": ".jobs-list-item",
        "title_selector": ".job-title",
        "fallback_url": "https://www.google.com/search?q=site:careers.rtx.com+project+manager+India",
    },
    {
        "id": "rollsroyce",
        "name": "Rolls-Royce India",
        "emoji": "👑",
        "domain": "Aerospace Engines",
        "color": "#10b981",
        "search_url": "https://careers.rolls-royce.com/search-jobs/?keywords=project+manager&location=India",
        "job_card_selector": ".job-list-item",
        "title_selector": ".job-title a",
        "fallback_url": "https://www.google.com/search?q=site:careers.rolls-royce.com+project+manager+India",
    },
    {
        "id": "bosch",
        "name": "Bosch India",
        "emoji": "🔧",
        "domain": "Automotive & IoT",
        "color": "#dc2626",
        "search_url": "https://www.bosch.in/careers/your-job-search/?query=project+manager",
        "job_card_selector": ".job-list-item",
        "title_selector": ".job-title",
        "fallback_url": "https://www.google.com/search?q=site:bosch.in+careers+project+manager",
    },
    {
        "id": "schneider",
        "name": "Schneider Electric",
        "emoji": "💡",
        "domain": "Energy Management",
        "color": "#22c55e",
        "search_url": "https://www.se.com/ww/en/about-us/careers/search-jobs-and-apply/#search=project%20manager&location=India",
        "job_card_selector": ".job-item",
        "title_selector": ".job-title",
        "fallback_url": "https://www.google.com/search?q=site:se.com+careers+project+manager+India",
    },
    {
        "id": "caterpillar",
        "name": "Caterpillar India",
        "emoji": "🏗️",
        "domain": "Industrial R&D",
        "color": "#f59e0b",
        "search_url": "https://careers.caterpillar.com/en/jobs/?search=project+manager&location=India",
        "job_card_selector": ".job-tile",
        "title_selector": ".job-title",
        "fallback_url": "https://www.google.com/search?q=site:careers.caterpillar.com+project+manager+India",
    },

    # ── INDIAN COMPANIES ──
    {
        "id": "ltts",
        "name": "L&T Technology Services",
        "emoji": "💻",
        "domain": "Engineering R&D",
        "color": "#0ea5e9",
        "search_url": "https://www.ltts.com/careers/search-job?search=project+manager",
        "job_card_selector": ".job-list-item",
        "title_selector": ".job-title",
        "fallback_url": "https://www.google.com/search?q=site:ltts.com+careers+project+manager",
    },
    {
        "id": "tasl",
        "name": "Tata Advanced Systems",
        "emoji": "🛡️",
        "domain": "Aerospace & Defence",
        "color": "#8b5cf6",
        "search_url": "https://www.tataadvancedsystems.com/careers",
        "job_card_selector": ".career-item",
        "title_selector": ".career-title",
        "fallback_url": "https://www.google.com/search?q=site:tataadvancedsystems.com+careers+project+manager",
    },
    {
        "id": "tatamotors",
        "name": "Tata Motors",
        "emoji": "🚗",
        "domain": "Automotive & EV",
        "color": "#3b82f6",
        "search_url": "https://careers.tatamotors.com/jobs/search?query=project+manager",
        "job_card_selector": ".job-item",
        "title_selector": ".job-title",
        "fallback_url": "https://www.google.com/search?q=site:careers.tatamotors.com+project+manager",
    },
    {
        "id": "mahindra",
        "name": "Mahindra & Mahindra",
        "emoji": "🚙",
        "domain": "Automotive & EV",
        "color": "#dc2626",
        "search_url": "https://careers.mahindra.com/search/?q=project+manager&locationsearch=India",
        "job_card_selector": ".job-result-item",
        "title_selector": ".job-title",
        "fallback_url": "https://www.google.com/search?q=site:careers.mahindra.com+project+manager+India",
    },

    # ── DEFENCE & PSU ──
    {
        "id": "hal",
        "name": "HAL India",
        "emoji": "🛩️",
        "domain": "Aerospace PSU",
        "color": "#7c3aed",
        "search_url": "https://hal-india.co.in/career",
        "job_card_selector": ".career-item, .job-item, tr",
        "title_selector": "td, .career-title",
        "fallback_url": "https://www.google.com/search?q=site:hal-india.co.in+career+project+engineer",
    },
    {
        "id": "drdo",
        "name": "DRDO",
        "emoji": "🔬",
        "domain": "Defence R&D",
        "color": "#4f46e5",
        "search_url": "https://www.drdo.gov.in/careers",
        "job_card_selector": ".career-item, .job-item, .notification-item",
        "title_selector": ".career-title, a",
        "fallback_url": "https://www.google.com/search?q=site:drdo.gov.in+careers+project+engineer",
    },
    {
        "id": "bel",
        "name": "BEL India",
        "emoji": "📡",
        "domain": "Defence Electronics",
        "color": "#0f766e",
        "search_url": "https://bel-india.in/career",
        "job_card_selector": ".career-row, tr, .job-item",
        "title_selector": "td a, .job-title",
        "fallback_url": "https://www.google.com/search?q=site:bel-india.in+career+project+engineer",
    },
    {
        "id": "bhel",
        "name": "BHEL",
        "emoji": "⚡",
        "domain": "Power Engineering",
        "color": "#0369a1",
        "search_url": "https://www.bhel.com/careers",
        "job_card_selector": ".career-item, .job-item, tr",
        "title_selector": "td, .career-title, a",
        "fallback_url": "https://www.google.com/search?q=site:bhel.com+careers+project+engineer",
    },
    {
        "id": "ntpc",
        "name": "NTPC Limited",
        "emoji": "🌱",
        "domain": "Clean Energy PSU",
        "color": "#15803d",
        "search_url": "https://www.ntpc.co.in/en/career",
        "job_card_selector": ".career-item, tr, .job-item",
        "title_selector": "td a, .job-title, a",
        "fallback_url": "https://www.google.com/search?q=site:ntpc.co.in+career+project+engineer",
    },
    {
        "id": "isro",
        "name": "ISRO",
        "emoji": "🚀",
        "domain": "Space Technology",
        "color": "#f97316",
        "search_url": "https://www.isro.gov.in/Careers.html",
        "job_card_selector": ".career-item, tr, li",
        "title_selector": "td, li, a",
        "fallback_url": "https://www.google.com/search?q=site:isro.gov.in+careers+scientist+engineer",
    },

    # ── EV & EMERGING ──
    {
        "id": "olaelectric",
        "name": "Ola Electric",
        "emoji": "⚡",
        "domain": "EV Manufacturing",
        "color": "#84cc16",
        "search_url": "https://olaelectric.com/careers",
        "job_card_selector": ".job-card, .career-item, [class*='job']",
        "title_selector": ".job-title, h3, h4",
        "fallback_url": "https://www.google.com/search?q=site:olaelectric.com+careers+project+manager",
    },
    {
        "id": "ather",
        "name": "Ather Energy",
        "emoji": "🛵",
        "domain": "EV & Clean Mobility",
        "color": "#06b6d4",
        "search_url": "https://www.atherenergy.com/careers",
        "job_card_selector": ".job-card, .career-item, [class*='job']",
        "title_selector": ".job-title, h3, h4",
        "fallback_url": "https://www.google.com/search?q=site:atherenergy.com+careers+project+manager",
    },
    {
        "id": "amazon",
        "name": "Amazon India (Infra)",
        "emoji": "📦",
        "domain": "E-commerce Infrastructure",
        "color": "#f97316",
        "search_url": "https://amazon.jobs/en/search?base_query=project+engineer&loc_query=India&job_type=Full-Time",
        "job_card_selector": ".job-tile",
        "title_selector": ".job-title",
        "fallback_url": "https://www.google.com/search?q=site:amazon.jobs+project+engineer+India",
    },
    {
        "id": "godrej",
        "name": "Godrej & Boyce",
        "emoji": "⚙️",
        "domain": "Precision Engineering",
        "color": "#10b981",
        "search_url": "https://www.godrejenterprises.com/careers",
        "job_card_selector": ".job-item, .career-item",
        "title_selector": ".job-title, a",
        "fallback_url": "https://www.google.com/search?q=site:godrej.com+careers+project+engineer",
    },
    {
        "id": "collins",
        "name": "Collins Aerospace India",
        "emoji": "✈️",
        "domain": "Aerospace Systems",
        "color": "#1e40af",
        "search_url": "https://careers.collinsaerospace.com/search-jobs/?keywords=project+manager&location=India",
        "job_card_selector": ".job-list-item",
        "title_selector": ".job-title",
        "fallback_url": "https://www.google.com/search?q=site:careers.collinsaerospace.com+project+manager+India",
    },
]

# ── YOUR PROFILE KEYWORDS ──
# These are matched against job titles and descriptions
PROFILE_KEYWORDS = [
    "capex", "capital expenditure", "project manager", "program manager",
    "pmo", "governance", "cost control", "budget", "variance",
    "cpm", "pert", "scheduling", "ms project", "power bi",
    "sap", "sap mm", "vendor", "procurement", "risk management",
    "mechanical", "manufacturing", "plant", "infrastructure",
    "epc", "shutdown", "wbs", "milestone", "project engineer",
    "program governance", "stakeholder", "commissioning",
    "capex management", "project planning", "contract management"
]

# ── SEARCH TERMS TO TRY ON EACH SITE ──
SEARCH_TERMS = [
    "project manager",
    "program manager",
    "project engineer",
    "capex",
    "pmo"
]
